version: '3'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 80:80
    links:
      - db
