version: '3'
services:
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    ports:
      - ${PORT}:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    links:
      - db
