version: '3'
services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    ports:
      - ${PORT}:8388
    environment:
      - METHOD
      - PASSWORD
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.application == shadowsocks-libev
